name: Build and Copy to NAS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build EXE
        run: |
          pip install pyinstaller
          pyinstaller --onefile script.py

      - name: Copy to NAS
        run: |
          copy dist\script.exe "\\192.168.1.20\Aplicaciones\Inventario\script.exe"
